export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/loginn'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket_product'
export const PRODUCT_ROUTE = '/producttt'